#include <stdio.h>
/**
 * main - Write a program that prints the first 50 Fibonacci numbers,
 * starting with 0.
 *
 * starting with 0.
 *
 * Return: the last digit of a number
 * --------------------------
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55,
 * 89. By considering the terms in the Fibonacci sequence whose
 * values do not exceed 4,000,000, write a program that finds and
 * prints the sum of the even-valued terms, followed by a new line.
 * --------------------------
 */
int main(void)
{
	unsigned long int a = 1, b = 2, next, sum = 0;

	/* Initialize variables a and b with the first two Fibonacci terms */
	/* and sum to keep track of the sum of even Fibonacci terms. */

	while (b <= 4000000)
	{
		/* Check if the current Fibonacci term (b) is even */
		if (b % 2 == 0)
		{
			/* If it's even, add it to the sum */
			sum += b;
		}

		/* Calculate the next Fibonacci number */
		next = a + b;
		a = b;
		b = next;

		/* Update a and b for the next iteration in the Fibonacci sequence */
	}

	/* Print the sum of even-valued Fibonacci terms not exceeding 4,000,000 */
	printf("%lu\n", sum);

	return (0);
}
